apiVersion: 1

datasources:
  - name: XProxy Tester MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: xproxy_tester
    user: xproxy
    secureJsonData:
      password: xproxy
    jsonData:
      maxOpenConns: 150
      maxIdleConns: 50
      connMaxLifetime: 14400
      timezone: UTC
      cacheTTL: 300
      queryTimeout: 60s
      timeInterval: 30s
    isDefault: true
    editable: true
    uid: xproxy-tester-mysql

